
api:
  port: 3000

database:
  host: localhost
  port: 5432
  name: owl # Database name
  user: owl # User name (optional)
  password: goomba # (optional)

testDatabase: # Optional
  host: localhost
  port: 5432
  name: owl.test

cors:
  originPatterns:
    - '^http://localhost(:\d*)?($|/)'
    - '^https://example.com($|/)'

youtube:
  key: API KEY HERE
